[package]
name = "ferris_elf"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon.workspace = true
rustc-hash.workspace = true
bytemuck.workspace = true
arrayvec.workspace = true
